title: Ginger Ink
tagline: Words with purpose
description: "A freelance communications service creating engaging content with your audience in mind. Competitive rates. Located in Wellington, New Zealand."
author: Nicole Skews-Poole
url: "http://gingerink.co.nz"
keywords:
  - communications
  - freelance
  - wellington
  - copywriting
  - content development
  - annual reports
  - copy writing
contact: "nicole@gingerink.co.nz"
image: "/assets/images/circle-logo2.png"
<img class="editable centered-image" src="/assets/images/contact-page-logo.png" width="200" height="282" alt="Ginger Ink logo" />