title:            Ginger Ink
tagline:          'Words with purpose'
description:      'Words with purpose'
author:           'Nicole Skews-Poole'
url:              http://gingerink.co.nz
keywords:
- First Keyword
- Second Keyword
- Third Keyword
contact:          nicole@gingerink.co.nz