title: Ginger Ink
tagline: Words with purpose
description: "A freelance communications service creating engaging content with your audience in mind. Competitive rates. Located in Wellington, New Zealand."
author: Nicole Skews-Poole
url: "http://gingerink.co.nz/"
keywords:
  - copywriting
  - content creation
  - new zealand
  - wellington 
  - auckland
  - communications
  - pr
  - public relations
  - freelance
  - content development
  - annual reports
  - copy writing
contact: "nicole@gingerink.co.nz"
image: "http://gingerink.co.nz/siteicon.png"




