title: Ginger Ink
tagline: Words with purpose
description: "Ginger Ink is a freelance communications service. We create tailored, engaging content just for you. And we don't charge the earth"
author: Nicole Skews-Poole
url: "http://gingerink.co.nz/"
keywords:
  - copywriting
  - content creation
  - new zealand
  - wellington 
  - auckland
  - communications
  - pr
  - public relations
  - freelance
  - content development
  - annual reports
  - copy writing
contact: "nicole@gingerink.co.nz"



