title:            Ginger Ink
tagline:          'Words with purpose'
description:      'Words with purpose'
url:              http://gingerink.co.nz
author:
  name:           'Nicole Skews-Poole'
  url:            http://gingerink.co.nz
