title: Ginger Ink
tagline: Words with purpose
description: "Providing high quality communications services like copywriting and content development at competitive rates. Located in Wellington, New Zealand."
author: Nicole Skews-Poole
url: "http://gingerink.co.nz"
keywords:
  - communications
  - copy writing
  - content
contact: "nicole@gingerink.co.nz"